import type { Rule } from "../types.js";

export function renderClaude(rules: Rule[]): string {
  const sections = new Map<string, Rule[]>();

  for (const rule of rules) {
    const existing = sections.get(rule.section) ?? [];
    existing.push(rule);
    sections.set(rule.section, existing);
  }

  // Sort rules within each section by priority
  for (const rules of sections.values()) {
    rules.sort((a, b) => b.priority - a.priority);
  }

  const lines: string[] = [
    "# CLAUDE.md",
    `<!-- Generated by foreman-context. Last updated: ${new Date().toISOString().split("T")[0]} -->`,
    `<!-- To regenerate: npx foreman-context update -->`,
    "",
  ];

  for (const [section, sectionRules] of sections) {
    lines.push(`## ${section}`, "");
    for (const rule of sectionRules) {
      lines.push(`- ${rule.text} <!-- source: ${rule.source} -->`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
